@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Azure region for the Redis cache.')
param location string = context.resource.location

var uniqueName = 'redis-${uniqueString(context.resource.id)}'

resource redis 'Microsoft.Cache/redis@2024-03-01' = {
  name: uniqueName
  location: location
  properties: {
    sku: {
      name: 'Basic'
      family: 'C'
      capacity: 0
    }
    enableNonSslPort: false
    minimumTlsVersion: '1.2'
    redisVersion: '6'
  }
}

var keys = redis.listKeys()

output result object = {
  resources: [
    redis.id
  ]
  values: {
    host: redis.properties.hostName
    port: redis.properties.sslPort
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    password: keys.primaryKey
  }
}
