@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Azure region for the Azure OpenAI resource.')
param location string = context.resource.location

@description('OpenAI model to deploy (e.g. gpt-4o-mini, gpt-4o).')
param model string = context.resource.properties.?model ?? 'gpt-4o-mini'

var uniqueName = 'oai-${uniqueString(context.resource.id)}'

resource account 'Microsoft.CognitiveServices/accounts@2024-10-01' = {
  name: uniqueName
  location: location
  kind: 'OpenAI'
  sku: {
    name: 'S0'
  }
  properties: {
    publicNetworkAccess: 'Enabled'
    disableLocalAuth: false
  }
}

resource deployment 'Microsoft.CognitiveServices/accounts/deployments@2024-10-01' = {
  parent: account
  name: model
  sku: {
    name: 'Standard'
    capacity: 1
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: model
    }
  }
}

output result object = {
  resources: [
    account.id
  ]
  values: {
    endpoint: account.properties.endpoint
    model: model
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    apiKey: account.listKeys().key1
  }
}
