@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Azure region for the Storage Account.')
param location string = context.resource.location

@description('Blob container name.')
param bucket string = context.resource.properties.?bucket ?? context.resource.name

var uniqueName = 'st${uniqueString(context.resource.id)}'

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: uniqueName
  location: location
  kind: 'StorageV2'
  sku: {
    name: 'Standard_LRS'
  }
  properties: {
    accessTier: 'Hot'
    supportsHttpsTrafficOnly: true
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: storageAccount
  name: 'default'
}

resource container 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: blobService
  name: bucket
  properties: {
    publicAccess: 'None'
  }
}

output result object = {
  resources: [
    storageAccount.id
  ]
  values: {
    endpoint: storageAccount.properties.primaryEndpoints.blob
    bucket: bucket
    #disable-next-line outputs-should-not-contain-secrets
    accessKey: storageAccount.listKeys().keys[0].value
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    secretKey: storageAccount.listKeys().keys[1].value
  }
}
