@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Azure region for the PostgreSQL Flexible Server.')
param location string = context.resource.location

@description('Name of the PostgreSQL database. Defaults to the name of the Radius resource.')
param database string = context.resource.name

@description('PostgreSQL administrator login name.')
param administratorLogin string = 'pgadmin'

@description('PostgreSQL administrator login password.')
@secure()
#disable-next-line secure-parameter-default
param administratorLoginPassword string = uniqueString(context.resource.id, 'pgpass')

@description('PostgreSQL major version.')
param version string = '16'

// Map Radius size property to Azure SKU
var skuMap = {
  S: { name: 'Standard_B1ms', tier: 'Burstable' }
  M: { name: 'Standard_D2ds_v5', tier: 'GeneralPurpose' }
  L: { name: 'Standard_D4ds_v5', tier: 'GeneralPurpose' }
}
var size = context.resource.properties.?size ?? 'S'
var sku = skuMap[size]

var uniqueName = 'pg-${uniqueString(context.resource.id)}'

resource server 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' = {
  name: uniqueName
  location: location
  sku: sku
  properties: {
    version: version
    administratorLogin: administratorLogin
    administratorLoginPassword: administratorLoginPassword
    storage: {
      storageSizeGB: 32
    }
    backup: {
      backupRetentionDays: 7
      geoRedundantBackup: 'Disabled'
    }
    highAvailability: {
      mode: 'Disabled'
    }
    authConfig: {
      passwordAuth: 'Enabled'
    }
    network: {
      publicNetworkAccess: 'Enabled'
    }
  }
}

// Create the application database
resource db 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01' = {
  parent: server
  name: database
  properties: {
    charset: 'UTF8'
    collation: 'en_US.utf8'
  }
}

// Allow Azure services to connect
resource firewallRule 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2024-08-01' = {
  parent: server
  name: 'AllowAzureServices'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
}

output result object = {
  resources: [
    server.id
  ]
  values: {
    host: server.properties.fullyQualifiedDomainName
    port: 5432
    database: database
    username: administratorLogin
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    password: administratorLoginPassword
  }
}
