@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

extension kubernetes with {
  kubeConfig: ''
  namespace: 'default'
} as kubernetes

var resourceName = context.resource.name
var namespace = context.runtime.kubernetes.namespace
var uniqueName = 'func-${uniqueString(context.resource.id)}'

var resourceProperties = context.resource.properties ?? {}
var image = resourceProperties.image

// Extract connection data from linked resources
var resourceConnections = context.resource.?connections ?? {}
var connectionDefinitions = context.resource.properties.?connections ?? {}
var excludedProperties = ['recipe', 'status', 'provisioningState']

// Build environment variables from connections
var connectionEnvVars = reduce(items(resourceConnections), [], (acc, conn) =>
  connectionDefinitions[conn.key].?disableDefaultEnvVars != true
    ? concat(acc, 
        reduce(items(conn.value ?? {}), [], (envAcc, prop) =>
          contains(excludedProperties, prop.key)
            ? envAcc
            : concat(envAcc, [{
                name: toUpper('CONNECTION_${conn.key}_${prop.key}')
                value: string(prop.value)
              }])
        )
      )
    : acc
)

// Ensure the target namespace exists
resource ns 'core/Namespace@v1' = {
  metadata: {
    name: namespace
  }
}

// Deploy as a Deployment (long-running worker) rather than CronJob
// so it can continuously poll the Redis queue
resource functionDeploy 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
  }
  spec: {
    replicas: 1
    selector: {
      matchLabels: {
        app: 'function'
        resource: resourceName
      }
    }
    template: {
      metadata: {
        labels: {
          app: 'function'
          resource: resourceName
          'radapp.io/application': context.application == null ? '' : context.application.name
        }
      }
      spec: {
        containers: [
          {
            name: 'worker'
            image: image
            env: connectionEnvVars
            resources: {
              requests: {
                memory: '128Mi'
              }
            }
          }
        ]
      }
    }
  }
}

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${functionDeploy.metadata.namespace}/providers/apps/Deployment/${functionDeploy.metadata.name}'
  ]
  values: {}
}
