@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Ollama model to pull on startup.')
param model string = context.resource.properties.?model ?? 'phi3:mini'

extension kubernetes with {
  kubeConfig: ''
  namespace: 'default'
} as kubernetes

var uniqueName = 'ollama-${uniqueString(context.resource.id)}'
var port = 11434
var namespace = context.runtime.kubernetes.namespace

// Ensure the target namespace exists
resource ns 'core/Namespace@v1' = {
  metadata: {
    name: namespace
  }
}

resource ollama 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
  }
  spec: {
    selector: {
      matchLabels: {
        app: 'ollama'
        resource: context.resource.name
      }
    }
    template: {
      metadata: {
        labels: {
          app: 'ollama'
          resource: context.resource.name
          'radapp.io/application': context.application == null ? '' : context.application.name
        }
      }
      spec: {
        containers: [
          {
            name: 'ollama'
            image: 'ollama/ollama:latest'
            ports: [
              {
                containerPort: port
              }
            ]
            resources: {
              requests: {
                memory: '2Gi'
              }
            }
            // Pull the model on startup via lifecycle hook
            lifecycle: {
              postStart: {
                exec: {
                  command: [
                    '/bin/sh'
                    '-c'
                    'sleep 5 && ollama pull ${model}'
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: {
      name: uniqueName
    }
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      app: 'ollama'
      resource: context.resource.name
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${ollama.metadata.namespace}/providers/apps/Deployment/${ollama.metadata.name}'
  ]
  values: {
    endpoint: 'http://${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local:${port}'
    model: model
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    apiKey: 'not-required-for-ollama'
  }
}
