@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Redis password')
@secure()
#disable-next-line secure-parameter-default
param password string = uniqueString(context.resource.id)

@description('Tag to pull for the Redis container image.')
param tag string = '7-alpine'

extension kubernetes with {
  kubeConfig: ''
  namespace: 'default'
} as kubernetes

var uniqueName = 'redis-${uniqueString(context.resource.id)}'
var port = 6379
var namespace = context.runtime.kubernetes.namespace

// Ensure the target namespace exists
resource ns 'core/Namespace@v1' = {
  metadata: {
    name: namespace
  }
}

resource redis 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
  }
  spec: {
    selector: {
      matchLabels: {
        app: 'redis'
        resource: context.resource.name
      }
    }
    template: {
      metadata: {
        labels: {
          app: 'redis'
          resource: context.resource.name
          'radapp.io/application': context.application == null ? '' : context.application.name
        }
      }
      spec: {
        containers: [
          {
            name: 'redis'
            image: 'redis:${tag}'
            ports: [
              {
                containerPort: port
              }
            ]
            command: [
              'redis-server'
              '--requirepass'
              password
            ]
            resources: {
              requests: {
                memory: '128Mi'
              }
            }
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: {
      name: uniqueName
    }
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      app: 'redis'
      resource: context.resource.name
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${redis.metadata.namespace}/providers/apps/Deployment/${redis.metadata.name}'
  ]
  values: {
    host: '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'
    port: port
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    password: password
  }
}
