@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('MinIO root user')
param rootUser string = 'minioadmin'

@description('MinIO root password')
@secure()
#disable-next-line secure-parameter-default
param rootPassword string = uniqueString(context.resource.id)

@description('Bucket name')
param bucket string = context.resource.properties.?bucket ?? context.resource.name

extension kubernetes with {
  kubeConfig: ''
  namespace: 'default'
} as kubernetes

var uniqueName = 'minio-${uniqueString(context.resource.id)}'
var port = 9000
var namespace = context.runtime.kubernetes.namespace

// Ensure the target namespace exists
resource ns 'core/Namespace@v1' = {
  metadata: {
    name: namespace
  }
}

resource minio 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
  }
  spec: {
    selector: {
      matchLabels: {
        app: 'minio'
        resource: context.resource.name
      }
    }
    template: {
      metadata: {
        labels: {
          app: 'minio'
          resource: context.resource.name
          'radapp.io/application': context.application == null ? '' : context.application.name
        }
      }
      spec: {
        containers: [
          {
            name: 'minio'
            image: 'minio/minio:latest'
            command: [
              'minio'
              'server'
              '/data'
            ]
            ports: [
              {
                containerPort: port
              }
            ]
            env: [
              {
                name: 'MINIO_ROOT_USER'
                value: rootUser
              }
              {
                name: 'MINIO_ROOT_PASSWORD'
                value: rootPassword
              }
            ]
            resources: {
              requests: {
                memory: '256Mi'
              }
            }
            // Create the default bucket on startup
            lifecycle: {
              postStart: {
                exec: {
                  command: [
                    '/bin/sh'
                    '-c'
                    'sleep 3 && mkdir -p /data/${bucket}'
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: {
      name: uniqueName
    }
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      app: 'minio'
      resource: context.resource.name
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${minio.metadata.namespace}/providers/apps/Deployment/${minio.metadata.name}'
  ]
  values: {
    endpoint: 'http://${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local:${port}'
    bucket: bucket
    accessKey: rootUser
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    secretKey: rootPassword
  }
}
